// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJHvUXCdVHQwcrKq6c586uuIHZcCHR8w',
    appId: '1:108943094326:web:a7169fb168935d03b05e97',
    messagingSenderId: '108943094326',
    projectId: 'doctor-appointment-71705',
    authDomain: 'doctor-appointment-71705.firebaseapp.com',
    storageBucket: 'doctor-appointment-71705.firebasestorage.app',
    measurementId: 'G-3WXL6GY19H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlekMRo4GT5SUxZ5O6hg-xmzAHZCBWQE',
    appId: '1:108943094326:android:c5f32214f3b9a087b05e97',
    messagingSenderId: '108943094326',
    projectId: 'doctor-appointment-71705',
    storageBucket: 'doctor-appointment-71705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFznJx4viuUFn9Zoek1ImMbBsAPZgKkg8',
    appId: '1:108943094326:ios:e7815c0db4cbb617b05e97',
    messagingSenderId: '108943094326',
    projectId: 'doctor-appointment-71705',
    storageBucket: 'doctor-appointment-71705.firebasestorage.app',
    iosBundleId: 'com.example.doctAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFznJx4viuUFn9Zoek1ImMbBsAPZgKkg8',
    appId: '1:108943094326:ios:e7815c0db4cbb617b05e97',
    messagingSenderId: '108943094326',
    projectId: 'doctor-appointment-71705',
    storageBucket: 'doctor-appointment-71705.firebasestorage.app',
    iosBundleId: 'com.example.doctAppointment',
  );
}
